language: node_js
node_js:
  - '12'
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run test:lib -- -- --watch=false --browsers=ChromeHeadless
  - npm run build:lib:prod
  - npm run test:app -- -- --watch=false --browsers=ChromeHeadless
  - npm run build:app:prod
  - cp docs/index.html docs/404.html

after_script:
  - cat ./coverage/password-strength-meter/lcov.info | coveralls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master
