language: node_js
node_js:
  - '10'
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run test:lib
  - npm run test:app
  - npm run build:lib
  - npm run build:app:prod
  - mv docs/index.html docs/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master
